# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep-learner',
                'doc_host': 'https://ryaneng97.github.io',
                'git_url': 'https://github.com/ryaneng97/deep-learner',
                'lib_path': 'deep_learner'},
  'syms': {'deep_learner.core': {'deep_learner.core.foo': ('core.html#foo', 'deep_learner/core.py')}}}
