# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep-learner',
                'doc_host': 'https://ryaneng97.github.io',
                'git_url': 'https://github.com/ryaneng97/deep-learner',
                'lib_path': 'deep_learner'},
  'syms': { 'deep_learner.core': {'deep_learner.core.foo': ('core.html#foo', 'deep_learner/core.py')},
            'deep_learner.training': { 'deep_learner.training.Dataset': ('book3.html#dataset', 'deep_learner/training.py'),
                                       'deep_learner.training.Dataset.__getitem__': ( 'book3.html#dataset.__getitem__',
                                                                                      'deep_learner/training.py'),
                                       'deep_learner.training.Dataset.__init__': ( 'book3.html#dataset.__init__',
                                                                                   'deep_learner/training.py'),
                                       'deep_learner.training.Dataset.__len__': ('book3.html#dataset.__len__', 'deep_learner/training.py'),
                                       'deep_learner.training.accuracy': ('book3.html#accuracy', 'deep_learner/training.py'),
                                       'deep_learner.training.fit': ('book3.html#fit', 'deep_learner/training.py'),
                                       'deep_learner.training.get_dls': ('book3.html#get_dls', 'deep_learner/training.py'),
                                       'deep_learner.training.report': ('book3.html#report', 'deep_learner/training.py')}}}
