# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/book3.ipynb.

# %% auto #0
__all__ = ['accuracy', 'report', 'Dataset', 'fit', 'get_dls']

# %% ../nbs/book3.ipynb #fa55decd-2bae-4be3-a707-611fb2a2055f
import pickle,gzip,math,os,time,shutil,torch,matplotlib as mpl,numpy as np,matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor,nn
import torch.nn.functional as F

# %% ../nbs/book3.ipynb #dc64dbcb-297d-4b97-8dbb-6909d5389699
def accuracy(out, yb): return (out.argmax(dim=1)==yb).float().mean()

# %% ../nbs/book3.ipynb #aa6f0eed-ac83-45f0-8726-009a57294cef
def report(loss, preds, yb): print(f'{loss:.2f}, {accuracy(preds, yb):.2f}')

# %% ../nbs/book3.ipynb #464da671-eb34-4975-a304-319c6a496304
class Dataset():
    def __init__(self, x, y): self.x,self.y = x,y
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i],self.y[i]

# %% ../nbs/book3.ipynb #8bcef704-dd4d-4b1a-84e4-92b497beead8
from torch.utils.data import DataLoader, SequentialSampler, RandomSampler, BatchSampler

# %% ../nbs/book3.ipynb #eeb2fd54-6f24-4e2b-8110-a6820cd2a73f
def fit(epochs, model, loss_func, opt, train_dl, valid_dl):
    for epoch in range(epochs):
        model.train()
        for xb,yb in train_dl:
            loss = loss_func(model(xb), yb)
            loss.backward()
            opt.step()
            opt.zero_grad()

        model.eval()
        with torch.no_grad():
            tot_loss,tot_acc,count= 0.,0.,0
            for xb,yb in valid_dl:
                pred = model(xb)
                n = len(xb)
                count += n
                tot_loss += loss_func(pred,yb).item()*n
                tot_acc += accuracy(pred,yb).item()*n
        print(epoch, tot_loss/count, tot_acc/count)
    return tot_loss/count, tot_acc/count

# %% ../nbs/book3.ipynb #ae867186-5e4e-43b0-be84-d02fe17ecf4a
def get_dls(train_ds, valid_ds, bs, **kwargs):
    return (DataLoader(train_ds, batch_size=bs, shuffle=True, **kwargs),
            DataLoader(valid_ds, batch_size=bs*2, **kwargs))
